const fs = require('fs');
const path = require('path');

const templatesDir = path.join(__dirname, 'src/functions/templates');
const files = fs.readdirSync(templatesDir);

let fileContents = {};

files.forEach(file => {
    const filePath = path.join(templatesDir, file);
    const content = fs.readFileSync(filePath, 'utf-8');

    // write the contents of the file to a variable with the same name as the file name
    const variableName = file.split('.')[0];
    fileContents[variableName] = content;
});

const tsFilePath = path.join(__dirname, 'src/functions/Templates.ts');

// write a warning at the top of the file to not edit the file directly
const warning = `// This file is generated by the compile.js script. Do not edit this file directly.\n\n`;
fs.writeFileSync(tsFilePath, warning);

// write each item in the fileContents array to the templates.ts file as a variable
let tsFileContent = '';
for (let key in fileContents) {
    tsFileContent += `export const ${key} = \`${fileContents[key]}\`;\n`;
}

fs.appendFileSync(tsFilePath, tsFileContent);