// This file is generated by the compile.js script. Do not edit this file directly.

export const error = `<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css" />
    <title>Import Lists from Twitter</title>
</head>

<body>
    <section id="app" class="hero is-fullheight">
        <div class="hero-body">
            <div class="container has-text-centered">
                <h1 class="title">Whoops</h1>
                <h2 class="subtitle">That didn't work for some reason.</h2>
                <div class="notification is-danger">
                    <p>{{message}}</p>
                </div>
            </div>
        </div>
    </section>
</body>

</html>`;
export const home = `<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css" />
    <title>Import Lists from Twitter</title>
</head>

<body>
    <section id="app" class="hero is-fullheight">
        <div class="hero-body">
            <div class="container has-text-centered">
                <h1 class="title">Import Urlist lists from Twitter</h1>
                <h2 class="subtitle">Click below to login to Twitter and have your existing lists migrated to
                    <b>{{newUserName}}</b> signed in with <b>{{newIdentityProvider}}</b>.
                </h2>
                <a class="button is-primary mt-4"
                    href="{{prodUri}}/.auth/login/twitter?post_login_redirect_uri={{baseUri}}/api/import?data={{data}}">Complete
                    Import</a>
            </div>
        </div>
    </section>
</body>

</html>`;
